### PR TITLE
Reduce the number of tasks created in the tests to prevent a cpu timeout error

### PR DESCRIPTION
**Pull request by force2b**

### CODE REVIEW

**Comment by cdcarter** [comment]
@davidhabib - we are seeing CPU timeouts in the ldv100k org in these two tests (LDV_Engagement_Plan_Task_Rollup_1+2). Mike has submitted this PR to reduce the amount of work performed in the tests.

It looks like we've dialed back the EP tests before https://github.com/SalesforceFoundation/Cumulus-LDV-Tests/commit/ad0733f623f8f6b8bfe215bb34889422191e4566. I wanted to get your 👍 on this before we do it on these tests too. They were at one point designed to run with 20...

**Comment by davidhabib** [comment]
@cdcarter I'm ok with us having to reduce these EP LDV tests to having 15 EP tasks per template.

@njjc @szeitz @judisohn  what are your thoughts?  what this really implies is that users will need to be cognizant of how many tasks they put in Engagement Plans, if they are hooking up those engagement plans to levels.  Because an org could certainly have many donors move up a level after all the data for a big fundraiser gets entered, and so seeing a batch of 200 contacts to apply an EP to may not be extreme.  It's really a case of how many tasks within the EP are reasonable.  15 seems like a high enough limit we could live with.  We aren't putting in a hard limit check; it's just that they will eventually run into system limits depending on how many tasks they put on an EP, and how many objects they try to apply the EP to at once.

**Comment by judisohn** [comment]
@davidhabib Is it possible for the Manage/Edit page to display a warning at let's say 10 tasks stating that they may run in to limits and should consider breaking up into smaller plans and that there's a hard limit of 15? That way when they hit the wall or start seeing some performance issues or limits hit, it's not a surprise.

**Comment by force2b** [comment]
Keep in mind that this is occurring in a unit test where there is other activity happening before the actual operation that fails. It might be worthwhile testing out the maximum number of tasks manually and/or through an import outside of a unit test to be sure we're eliminating any of the test overhead or limits.

**Comment by davidhabib** [comment]
like many areas where we hit limits, it all depends on the org's setup, and the interaction with 3rd party apps, workflow rules, custom triggers, etc.  Thus I am hesitant to add any sort of warning with a specific limit number because it really isn't a true hard and fast number.  We either target it too low, and needlessly warn, or we target too high, and customers get a false sense of what they can do.

**Comment by judisohn** [comment]
To me it feels like what happens with data skew. General rule of thumb is to make sure that you have less than 10K child records for any single parent... but I've heard of organizations with 5-10K that hit problems, and others with 800K that don't. But once you go significantly over 10K the odds are significantly higher. So I'm still advocating for some sort of visual clue whatever we decide is too many, with perhaps a 'dismiss' option that keeps it away for that EP once acknowledged.

**Comment by njjc** [comment]
I don't like the idea of displaying a warning for something that's non deterministic. There are lots of places where users can hit platform limits; can we let users lower the batch size in the rare case that the combination of number of tasks and batch size hit CPU timeouts?

**Pull request merged**
