### PR TITLE
Adding LDV tests for npe4__Relationship__c DML operations

### PR DESCRIPTION
**Pull request by dospromptman**
Note that two of the tests currently fail in my 1k org.

LDV_Relationship_Delete_1 fails due to SalesforceFoundation/Cumulus#1812

LDV_Relationship_Update_1 fails due to heap size limit exception.  Note that using a different field for gender causes an Internal Salesforce Error in my 1k test org.  See comment in test.

In general, I'm not sure why these LDV tests should have assertions, because they're meant to test limit exceptions.  I added assertions because I saw them being done in other LDV tests.  If necessary, I can remove them.

### CODE REVIEW

**Comment by davidhabib** [comment]
Good that you entered an issue about The LDV_Relationship_Delete_1 failure.  Once that issue gets addressed, and the LDV buidl passes, then we can include this test.

But the issue with LDV_Relationship_Update_1 hitting heap size limits needs to be investigated further.  Is this due to a bug in our code, or are we hitting a reasonable limit we cannot avoid?  If the latter, then you should reduce the number of objects you are dealing with until you can get it to pass, and we should be able to explain why the limitation.  thanks.

**Comment by dospromptman** [comment]
The LDV tests for relationships were failing because those tests were trying to perform dml operations on lists of records that contained mutual reciprocal relationships.  If there are two relationships in a list that each refer to the other for their reciprocal relationship, then bad things happen when you try to perform dml on that list.

In the case of delete, some reciprocal relationships do not get deleted because of the bug already noted.

In the case of update, this leads to infinite trigger recursion.  In this case the LDV test was failing due to updating the type of relationship on either side of the relationship with incompatible values.  This caused the two records to have their type updated again, ad infinitum.

Performing DML on lists of relationships that contain mutually reciprocal relationships is very problematic.  

I've decided to avoid the whole situation in these LDV tests by just making sure I only perform DML on lists that do not contain relationships that refer to other relationships in the list.

All LDV tests pass now.

**Comment by kbromer** [comment]
Curious about this bit: "In the case of update, this leads to infinite trigger recursion." 

Typically, the platform blocks more than 2 iterations for exactly that reason - is it truly infinite, or just more than 1?

**Comment by dospromptman** [comment]
The platform does prevent the trigger from recursing forever.  What I meant is that if the platform itself did not terminate the recursion, it would have been infinite.

However, with different batch sizes, even with the platform terminating the recursion, it is still enough to cause a problem.  With small batch sizes the issue presents as just failing to update some of the records to the "correct" type.  With a batch size of 200, it was throwing a heap size limit, presumably because of all of the extra work it was doing for each record.  When I included a large gender field from Contact (like Description), it crashed with an "Internal Salesforce Error", which I'm assuming was a more severe version of the heap size limit exception.

**Comment by kbromer** [comment]
Stack Trace ID for the Internal Salesforce Error?

**Comment by njjc** [comment]
It was 1719597232-254952 (-23874954) I believe

**Comment by kbromer** [comment]
String being cast as a bool somewhere:   java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean

Apex Stack Trace At Last Failure:
TDTM_TriggerHandler:run_rvoid_0Boolean_1Boolean_2Boolean_3Boolean_4Boolean_5Boolean_6List$$lSObject$$r_7List$$lSObject$$r_8Schema$$dDescribeSObjectResult_9TDTM_iTableDataGateway(java/lang/Boolean, java/lang/Boolean, java/lang/Boolean, java/lang/Boolean, java/lang/Boolean, java/lang/Boolean, com/salesforce/api/fast/List$$lcom/salesforce/api/entity/SObject$$r, com/salesforce/api/fast/List$$lcom/salesforce/api/entity/SObject$$r, com/salesforce/api/Schema/DescribeSObjectResult, TDTM_iTableDataGateway):97
__sfdc_trigger/TDTM_Relationship:invoke():34
<external code>

**Pull request merged**
